<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E4HH55MS" failures="1" tests="2" name="Test" time="5.107" errors="0" timestamp="2022-11-01T08:22:32 PDT">
  <testcase classname="testng.TimeOutTest" name="FirstTest" time="2.027"/>
  <testcase classname="testng.TimeOutTest" name="secondTest" time="3.017">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testng.TimeOutTest.secondTest() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng.TimeOutTest.secondTest() didn't finish within the time-out 3000
at java.base@18.0.2.1/java.lang.Thread.sleep(Native Method)
at app//testng.TimeOutTest.secondTest(TimeOutTest.java:15)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d10c00.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$MH/0x0000000800d11400.invoke(LambdaForm$MH)
at java.base@18.0.2.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Test -->
